[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Projects"
  identifier = "Projects"
  weight = -109
# Add any projects you'd like to list under here
[[main]]
  parent = "Projects"
  name = "Digital Bike Speedometer"
  url = "projects/bike_speedometer/"
[[main]]
  parent = "Projects"
  name = "Exalted Sage"
  url = "projects/exalted-sage/"

[[main]]
  name = "Hobbies"
  identifier = "Hobbies"
  weight = -108
[[main]]
  parent = "Hobbies"
  name = "Reading List"
  url = "hobbies/reading/"
[[main]]
  parent = "Hobbies"
  name = "Gaming"
  url = "hobbies/gaming/"
[[main]]
  parent = "Hobbies"
  name = "Health & Fitness"
  url = "hobbies/health_fitness/"

# [[main]]
#   name = "Archives"
#   url = "post/rich-content/"
#   weight = -107

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/Incapamentum/"
#[[social]]
#  name = "twitter"
#  weight = 2
#  url = "https://twitter.com/#"
[[social]]
  name = "linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/diazg-gustavoa/"
#[[social]]
#  name = "rss"
#  weight = 4
#  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"

# Submenus are done this way: parent -> identifier
#[[main]]
#  name = "Links"
#  identifier = "Links"
#  weight = -108
#[[main]]
#  parent = "Links"
#  name = "LinkedIn"
#  url = "https://www.linkedin.com/"
#[[main]]
#  parent = "Links"
#  name = "Twitter"
#  url = "https://twitter.com/"